version: "3.8"
services:
  dev-env:
    image: dev:1.0.0
    container_name: dev-env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME:$HOME
      #- /mnt:/mnt
      - $HOME/.gitconfig:$HOME/.gitconfig:ro
      - $HOME/.ssh:$HOME/.ssh:ro
      - /tmp/nvim-socket:/tmp/nvim-socket
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
    working_dir: /root
    tty: true
    stdin_open: true

